# Base Image
FROM node:20

# Working Directory
WORKDIR /app

# Files Copy
COPY package*.json ./

# Run Command During Build
RUN npm install

# Copy Remaining Code
COPY . .

# Default Command
CMD ["npm", "start"]